# hyprpaper.conf — v0.8.x hyprlang format
# path can be a directory — hyprpaper will load all images from it
# Waypaper handles switching; hyprpaper just needs to know the folder

splash = 0
ipc = 1

wallpaper {
    monitor =
    path = $HOME/Videos/Pictures/wallpapers/static/wallhaven-rrljjq.jpg
    fit_mode = cover
}
