################
### MONITORS ###
################

# NOTE: Change these to match your display setup
# Run `hyprctl monitors` to find your monitor names and supported resolutions
monitor=,2560x1600@165,auto,1.25

monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1

xwayland {
  force_zero_scaling = true
}
